/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom2atbm.view;

import com.nhom2atbm.model.Column;
import com.nhom2atbm.service.ColumnService;
import static java.lang.Boolean.TRUE;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGUYỄN HOÀNG
 */
public class capQuyenFrame extends javax.swing.JFrame {

    ColumnService columnService;

    /**
     * Creates new form capQuyenFrame
     */
    public capQuyenFrame() {
        initComponents();

        DefaultTableModel defaultTableModel = new DefaultTableModel() {
            @Override
            public Class getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 0 ->
                        String.class;
                    case 1 ->
                        Boolean.class;
                    case 2 ->
                        Boolean.class;
                    case 3 ->
                        Boolean.class;
                    default ->
                        Boolean.class;
                };
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };

        tbCapQuyen.setModel(defaultTableModel);
        tbCapQuyen.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        defaultTableModel.addColumn("Permission");
        defaultTableModel.addColumn("Grant");
        defaultTableModel.addColumn("With grant option");
        defaultTableModel.addColumn("Revoke");
        defaultTableModel.addRow(new Object[]{"SELECT", false, false, false});
        defaultTableModel.addRow(new Object[]{"INSERT", false, false, false});
        defaultTableModel.addRow(new Object[]{"UPDATE", false, false, false});
        defaultTableModel.addRow(new Object[]{"DELETE", false, false, false});
        tbCapQuyen.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioUser = new javax.swing.JRadioButton();
        radioRole = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listColumn = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listNameObj = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbCapQuyen = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CẤP QUYỀN CHO USER/ROLE");

        jLabel2.setText("Bạn muốn cấp quyền cho:");

        buttonGroup1.add(radioUser);
        radioUser.setText("User");
        radioUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUserActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioRole);
        radioRole.setText("Role");
        radioRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRoleActionPerformed(evt);
            }
        });

        jLabel5.setText("Cấp trên TABLE:");

        listTable.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "NHANVIEN", "PHONGBAN", "DIADIEM_PHG", "DEAN", "PHANCONG", "THANNHAN" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTable.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTableValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listTable);

        jLabel6.setText("Cấp trên cột:");

        listColumn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(listColumn);

        jScrollPane3.setViewportView(listNameObj);

        jLabel7.setText("Tên đối tượng được cấp: ");

        btnSubmit.setText("Xác nhận");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        tbCapQuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbCapQuyen.setColumnSelectionAllowed(true);
        tbCapQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCapQuyenMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbCapQuyen);
        tbCapQuyen.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioUser, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioRole, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(radioUser)
                                .addComponent(radioRole))
                            .addComponent(jLabel7))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSubmit)
                .addGap(332, 332, 332))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listTableValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTableValueChanged
        // TODO add your handling code here:
        if (listTable.getSelectedIndex() != -1) {
            try {
                columnService = new ColumnService();
                String tbName = listTable.getSelectedValue();
                List<Column> columns = columnService.getAllColumns(tbName);

                DefaultListModel<String> defaultListModel = new DefaultListModel<>();
                columns.forEach(co -> {
                    defaultListModel.addElement(co.getColumnName());
                });
                listColumn.setModel(defaultListModel);
            } catch (NullPointerException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_listTableValueChanged

    private void radioUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUserActionPerformed
        // TODO add your handling code here:
        columnService = new ColumnService();
        if (radioUser.isSelected()) {

            try {

                List<Column> columns = columnService.getAllUsers();
                DefaultListModel<String> defaultListModel = new DefaultListModel<>();
                columns.forEach(co -> {
                    defaultListModel.addElement(co.getColumnName());
                });
                listNameObj.setModel(defaultListModel);
            } catch (NullPointerException ex) {
                System.out.println(ex);
            }
        }

    }//GEN-LAST:event_radioUserActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        columnService = new ColumnService();
        // kiem tra cac radio button duoc check ko
        if (radioUser.isSelected() || radioRole.isSelected()
                && listNameObj.getSelectedIndex() != -1 && listTable.getSelectedIndex() != -1) {
            try {
                // cap quyen select co the cap den muc cot
                Boolean grantVal = (Boolean) tbCapQuyen.getValueAt(0, 1);
                Boolean waoVal = (Boolean) tbCapQuyen.getValueAt(0, 2);
                if (listColumn.getSelectedIndex() != -1) {
                    List<String> listCol;
                    listCol = listColumn.getSelectedValuesList();
                    
                    if (grantVal && !waoVal) {
                        columnService.CapQuyen("SELECT", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 0, listCol);
                    }
                    if (grantVal && waoVal) {
                        columnService.CapQuyen("SELECT", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 1, listCol);
                    }
                } else {
                    if (grantVal && !waoVal) {
                        columnService.CapQuyen("SELECT", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 0, null);
                    }
                    if (grantVal && waoVal) {
                        columnService.CapQuyen("SELECT", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 1, null);
                    }
                }

                // cap quyen insert khong cho cap den muc cot
                Boolean grantVal2 = (Boolean) tbCapQuyen.getValueAt(1, 1);
                Boolean waoVal2 = (Boolean) tbCapQuyen.getValueAt(1, 2);
                if (grantVal2 && !waoVal2) {
                    columnService.CapQuyen("INSERT", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 0, null);
                }
                if (grantVal2 && waoVal2) {
                    columnService.CapQuyen("INSERT", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 1, null);
                }

                // cap quyen update co the cap den muc cot
                Boolean grantVal3 = (Boolean) tbCapQuyen.getValueAt(2, 1);
                Boolean waoVal3 = (Boolean) tbCapQuyen.getValueAt(2, 2);
                if (listColumn.getSelectedIndex() != -1) {
                    List<String> listCol;
                    listCol = listColumn.getSelectedValuesList();
                    
                    if (grantVal3 && !waoVal3) {
                        columnService.CapQuyen("UPDATE", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 0, listCol);
                    }
                    if (grantVal3 && waoVal3) {
                        columnService.CapQuyen("UPDATE", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 1, listCol);
                    }
                } else {
                    if (grantVal3 && !waoVal3) {
                        columnService.CapQuyen("UPDATE", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 0, null);
                    }
                    if (grantVal3 && waoVal3) {
                        columnService.CapQuyen("UPDATE", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 1, null);
                    }
                }

                // cap quyen delete khong duoc cap den muc cot
                Boolean grantVal4 = (Boolean) tbCapQuyen.getValueAt(3, 1);
                Boolean waoVal4 = (Boolean) tbCapQuyen.getValueAt(3, 2);
                if (grantVal4 && !waoVal4) {
                    columnService.CapQuyen("DELETE", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 0, null);
                }
                if (grantVal4 && waoVal4) {
                    columnService.CapQuyen("DELETE", listTable.getSelectedValue(), listNameObj.getSelectedValue(), 1, null);
                }
                
                //thu hoi quyen tren bang cua user hoac role
                //thu hoi quyen select
                Boolean sel_Rev_Val = (Boolean) tbCapQuyen.getValueAt(0, 3);
                if (sel_Rev_Val) {
                    columnService.thuhoiQuyen("SELECT", listTable.getSelectedValue() , listNameObj.getSelectedValue());
                }
                
                //thu hoi quyen insert
                Boolean ins_Rev_Val = (Boolean) tbCapQuyen.getValueAt(1, 3);
                if (ins_Rev_Val) {
                    columnService.thuhoiQuyen("INSERT",listTable.getSelectedValue(), listNameObj.getSelectedValue());
                }
                
                //thu hoi quyen delete
                Boolean del_Rev_Val = (Boolean) tbCapQuyen.getValueAt(3, 3);
                if (del_Rev_Val) {
                    columnService.thuhoiQuyen("DELETE", listTable.getSelectedValue(), listNameObj.getSelectedValue());
                }
                
                //thu hoi quyen update
                Boolean upd_Rev_Val = (Boolean) tbCapQuyen.getValueAt(2, 3);
                if (upd_Rev_Val) {
                    columnService.thuhoiQuyen("UPDATE", listTable.getSelectedValue(), listNameObj.getSelectedValue());
                }
                
                
            } catch (NullPointerException ex) {
                System.out.println(ex);
            }

        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void radioRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRoleActionPerformed
        // TODO add your handling code here:
        columnService = new ColumnService();
        if (radioRole.isSelected()) {
            try {
                List<Column> columns = columnService.getAllRoles();
                DefaultListModel<String> defaultListModel = new DefaultListModel<>();
                columns.forEach(co -> {
                    defaultListModel.addElement(co.getColumnName());
                });
                listNameObj.setModel(defaultListModel);
            } catch (NullPointerException ex) {
                System.out.println(ex);
            }
            
            
        }
    }//GEN-LAST:event_radioRoleActionPerformed

    private void tbCapQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCapQuyenMouseClicked
        // TODO add your handling code here:
        Boolean b = (Boolean) tbCapQuyen.getValueAt(1, 1);
        Boolean b2 = (Boolean) tbCapQuyen.getValueAt(3, 1);
        if (b || b2) {
            listColumn.setEnabled(Boolean.FALSE);
        } else {
            listColumn.setEnabled(Boolean.TRUE);
        }
    }//GEN-LAST:event_tbCapQuyenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(capQuyenFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(capQuyenFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(capQuyenFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(capQuyenFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new capQuyenFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listColumn;
    private javax.swing.JList<String> listNameObj;
    private javax.swing.JList<String> listTable;
    private javax.swing.JRadioButton radioRole;
    private javax.swing.JRadioButton radioUser;
    private javax.swing.JTable tbCapQuyen;
    // End of variables declaration//GEN-END:variables
}
